# NumPy Practice

This notebook gives you hands-on practice with the core NumPy skills from `01_Introduction_to_Numpy.ipynb`. You will create arrays in several ways, inspect their properties, reshape and index into them, and apply arithmetic operations — both element-wise and along a specific axis. Work through the challenges in order, as later ones build on earlier results.

---

## Starter Code

In [1]:
# Import NumPy — run this cell first
import numpy as np

## Part 1 — Creating Arrays

### Challenge 1: Array from a list

Create a NumPy array from the following Python list:

```python
my_list = [1, 2, 5, 6, 8]
```

Print the array and its `dtype`.

In [2]:
# YOUR CODE HERE
my_list = [1, 2, 5, 6, 8]
np.array(my_list)

array([1, 2, 5, 6, 8])

### Challenge 2: Range array

Create a NumPy array containing the integers from **1 to 10** (inclusive).

In [3]:
# YOUR CODE HERE
np.arange(1, 11, dtype=int)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Challenge 3: Float range array

Create a NumPy array from **0 to 5** with a step size of **0.2**.

In [4]:
# YOUR CODE HERE
np.arange(0, 5.2, step=0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. ])

### Challenge 4: Random array

Create a NumPy array with shape **(2, 3)** filled with random values between 0 and 1.

In [5]:
# YOUR CODE HERE
np.random.rand(2, 3)

array([[0.3618758 , 0.69351088, 0.22677123],
       [0.89836693, 0.56156383, 0.05744329]])

---

## Part 2 — Manipulating Arrays

### Challenge 5: Array with mixed-type input

Create a NumPy array from the values `(1, 3, '4', 7, 12, '0')`. Force the data type to **integer** using the `dtype` parameter.

> Notice that the string values `'4'` and `'0'` are silently cast to integers. NumPy arrays are homogeneous — all elements must share the same type.

In [6]:
# YOUR CODE HERE
my_arr = np.array((1, 3, '4', 7, 12, '0'), dtype=int)

### Challenge 6: Inspect dtype and shape

Using the array you created in Challenge 5, check:
- The **data type** of the elements
- The **shape** of the array

In [7]:
# YOUR CODE HERE
np.shape(my_arr)
my_arr.dtype

dtype('int64')

### Challenge 7: Update a value by index

Update the **4th element** (index 3) of the array from Challenge 5 to the value `30`.

In [8]:
# YOUR CODE HERE
my_arr[3] = 30

### Challenge 8: Reshape to a 2×3 matrix

Reshape the array from Challenge 7 into a **2-row, 3-column** matrix. Print the result.

In [9]:
# YOUR CODE HERE
my_arr = my_arr.reshape(2, 3)
print(my_arr)

[[ 1  3  4]
 [30 12  0]]


### Challenge 9: Row-wise addition

Using the 2×3 matrix from Challenge 8:
- Add **8** to every value in the **first row**
- Add **12** to every value in the **second row**

> Hint: index the rows and assign back in place.

In [10]:
# YOUR CODE HERE
print(my_arr - [[8], [0]])
print(my_arr + [[0],[12]])

[[-7 -5 -4]
 [30 12  0]]
[[ 1  3  4]
 [42 24 12]]


### Challenge 10: Column-wise multiplication

Multiply the columns of your matrix:
- **First column** × 2
- **Second column** × 3
- **Third column** × 4

> Hint: you can do this in one line using broadcasting with a 1D array `[2, 3, 4]`.

In [11]:
# YOUR CODE HERE
my_arr[:, 0] * 2

my_arr * np.array([2, 3, 4])

array([[ 2,  9, 16],
       [60, 36,  0]])

### Challenge 11: Row sums

Calculate the **sum of all values in each row** of your matrix. You should get two totals — one per row.

In [12]:
# YOUR CODE HERE
my_arr.sum(axis=1)

array([ 8, 42])

### Challenge 12: Column maximums

Find the **largest value in each column** of your matrix. You should get three values — one per column.

In [13]:
# YOUR CODE HERE
my_arr.max(axis=0)

array([30, 12,  4])

### Challenge 13: Index a single element

Extract the value from the **second column, first row** of your matrix.

> Reminder: NumPy uses `array[row, column]` indexing.

In [14]:
# YOUR CODE HERE
my_arr[0, 1]

np.int64(3)

### Challenge 14: Find the index of a specific value

Find the **index** of the value `48` in your matrix.

> Hint: use `np.where()`. Note that depending on how your array evolved across previous challenges, your value at a given position may differ — first check what values are currently in the matrix.

In [18]:
# YOUR CODE HERE
print(my_arr)
np.where(my_arr == 12)

[[ 1  3  4]
 [30 12  0]]


(array([1]), array([1]))